// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessionmgr} from '../models';
import {domain} from '../models';
import {eksmgr} from '../models';
import {ssmmgr} from '../models';

export function AddIntegration(arg1:sessionmgr.AddIntegrationInput):Promise<domain.Integration>;

export function CancelLogin(arg1:string):Promise<void>;

export function ConnectSSM(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteIntegration(arg1:string):Promise<void>;

export function EKSSetupStatus():Promise<eksmgr.SetupStatus>;

export function GetSettings():Promise<domain.Settings>;

export function ListEKSClusters(arg1:string,arg2:string):Promise<Array<eksmgr.Cluster>>;

export function ListIntegrations():Promise<Array<domain.Integration>>;

export function ListSSMInstances(arg1:string,arg2:string):Promise<Array<ssmmgr.Instance>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function Login(arg1:string):Promise<void>;

export function Logout(arg1:string):Promise<void>;

export function SSMPluginStatus():Promise<ssmmgr.SetupStatus>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetProfileName(arg1:string,arg2:string):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function UpdateEKSKubeconfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateIntegration(arg1:string,arg2:sessionmgr.AddIntegrationInput):Promise<void>;

export function UpdateSettings(arg1:domain.Settings):Promise<void>;

export function Version():Promise<string>;
