// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIntegration(arg1) {
  return window['go']['main']['App']['AddIntegration'](arg1);
}

export function CancelLogin(arg1) {
  return window['go']['main']['App']['CancelLogin'](arg1);
}

export function ConnectSSM(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSSM'](arg1, arg2, arg3);
}

export function DeleteIntegration(arg1) {
  return window['go']['main']['App']['DeleteIntegration'](arg1);
}

export function EKSSetupStatus() {
  return window['go']['main']['App']['EKSSetupStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListEKSClusters(arg1, arg2) {
  return window['go']['main']['App']['ListEKSClusters'](arg1, arg2);
}

export function ListIntegrations() {
  return window['go']['main']['App']['ListIntegrations']();
}

export function ListSSMInstances(arg1, arg2) {
  return window['go']['main']['App']['ListSSMInstances'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function SSMPluginStatus() {
  return window['go']['main']['App']['SSMPluginStatus']();
}

export function SetPinned(arg1, arg2) {
  return window['go']['main']['App']['SetPinned'](arg1, arg2);
}

export function SetProfileName(arg1, arg2) {
  return window['go']['main']['App']['SetProfileName'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function UpdateEKSKubeconfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEKSKubeconfig'](arg1, arg2, arg3);
}

export function UpdateIntegration(arg1, arg2) {
  return window['go']['main']['App']['UpdateIntegration'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
